### ISSUE TITLE
1. Manual input for electricity consumption data (corrected version)

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#1]
## Value proposition

**As a** user,
**I want to** add a new energy consumption data
**so that** so that I have an overview about them and also have the information up-to-date.

## Description

<img width="640" alt="img1" src="https://user-images.githubusercontent.com/104724279/175505773-d320b1ee-66d5-43cb-bdfc-25677127029e.png">

## Acceptance criteria

- [x] Screen should scroll y (vertical), not x (horizontal)
- [x] There is a data input field
- [x] Whitespace is trimmed
- [x] Empty input data are not added
- [x] Only positiv numbers are allowed as input
- [x] Maxlength is 20 digits
- [x] Numbers together with actual date are added at list
- [x] Date shows the actual date
- [x] Display latest input with date and value on top of the list

## Complexity

Small to medium

## Tasks

- [x] Setup: branch, component, storybook, specs
- [x] Implement a field with the actual date on the top of input dialog
- [x] Create an input field
- [x] The actual date is shown at the top
- [x] Place button „Submit“
- [x] Add state for input data
- [x] Create List of input data
- [x] Show latest input with date and value on top of the list
- [x] Add base styles

**Comment by PReichetanz** [comment]
Hello Kim,
this is a good start!

I want to leave some questions / ideas to consider:

- As a value proposition, I would start with "...so that I have an overview about them." (because this is what you are doing **right now**).
- Is the input field on the left a real input element or rather a button which opens a form? If so, it should be labeled with "Add new data" or something similar.
- Having said that, I don't see the difference between the input element on the left and on the right, although it cannot both be an input field / a submit button.
- What does the Smiley with "Input ok" mean? Does it pop up as soon as you have added something to the `<Your Input>` field? If so, you better outsource this feature to another user story.
- Where is the data you put into the form is going to be displayed? Please add a scribble for this as well.
- I don't understand the first acceptance criteria: What numbers? How are they added with a date? Do you mean "They are saved together"?
- If you only allow numbers and separators as input values, do you still need to trim whitespaces (can the user still input whitespace?).
- Task "Show latest input with date and value": Where exactly and how is this value displayed? I assume you mean the red box next to the "Date" area? Please be more explicit about this.

**Comment by isabellpaulmann** [comment]
Finde ich gut 👍  Vielleicht sollte der Submit Button nicht über die komplette Breite gehen und der hinzufügte Input beim Eingang in die Liste eine kurze Animation z.B. ein 2sec faded Background bekommen, damit man sieht das es geklappt hat. :D

**Comment by smilenow24** [comment]
> Finde ich gut 👍 Vielleicht sollte der Submit Button nicht über die komplette Breite gehen und der hinzufügte Input beim Eingang in die Liste eine kurze Animation z.B. ein 2sec faded Background bekommen, damit man sieht das es geklappt hat. :D

Danke für die sehr guten Hinweise - diese werden ich später berücksichtigen; Zunächst habe ich die Funktionalität auf das nötigste reduziert; meine erste Version des issues war bereits zu overloaded und im musst "zurückbauen";

**Comment by JessicaLoers** [comment]
**Hi Kim** 
You have already worked diligently on this user story. Let's try to improve it together. 🙂
I have some comments you may think about before moving further

**Value proposition**
From a user perspective, I need this feature to add entries.
So I would suggest to write something like this:

**As a** User
**I want to** add a new energy consumption data  
**So that I** have my energy consumption information up-to-date

**Description**
The current date, displayed in the scribble, is not mentioned in this user story. The scribble should only contain features that you have either implemented in previous User Stories or in this User Story.  

**Acceptance criteria**
List should scroll y, not x ->  do you mean "should scroll vertically"? If so, maybe it's better to understand ;) 

**Tasks**

- The actual date is shown at the top:  **_could be a single User Story_**
- Show latest input with date and value on top of the list:  **_could also be an Acceptance criteria_** 🙂

I would recommend that you first work with rendering static entries. For example a User Story like "Show list of all entries". But of cause it's up to you to combine the features for creating and reading entries.

If you have any questions, feel free to ask. ✌️

**Comment by smilenow24** [comment]
@JessicaLoers - Thanks a lot for your comment 👍 - i have I used your hints to further improve my user story. I hope you like the result. 🙂
