### ISSUE TITLE
8. Edit functionality - with adapted input dialog

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#11]
## Value proposition

**As a** user,
**I want to** get displayed a third category (car)
**so that** so that I can also track and evaluate my energy consumption for car-mobility

## Description

-/-

## Acceptance criteria

- [ ] Tests and storybook work fine
- [ ] Category-field is visible and shows calculation value
- [ ] Category-field-button links to input-dialog for car-mobility
- [ ] Input-dialog shows analytic calculation and charts
- [ ] Category input-dialog works fine

## Complexity

small to medium

## Tasks

- [ ] Create branch
- [ ] Setup: Extended specs / storybook
- [ ] Create new category-field on dashboard
- [ ] Adapt category-field with according variables / icon
- [ ] Create category-field-button with link to according-dialog
- [ ] Adapt input-dialog for car-mobility-use with data for km
- [ ] Advance input-object for implementation of this categories
- [ ] Change call of input data according to the new object structur
