### ISSUE TITLE
7. Further development of reward / feedback / message system

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#13]
## Value proposition

**As a** user,
**I want to** get feedback about my inputs through a feedback / message system
**so that** I can quickly see if my energy consumption behavior is within my budget

## Description

<img width="622" alt="img-reward-system" src="https://user-images.githubusercontent.com/104724279/178201139-bb8f45b9-1bad-4d32-92be-bc2fca4f4272.png">

## Acceptance criteria

- [ ] Run fine: spec, storybook, component
- [x] Feedback, messages are shown
- [x] Smile-Icon change color and mimic correctly 
- [x] Condition 1 and 2 works fine

## Complexity

medium to large

## Tasks

- [x] Create branch
- [x] Extend data in message-object for for every situation
- [x] Smile-Icon conditional behavior
- [x] Smile-Icon condition color
- [x] Integrate conditional colored arrow in every category-button-field with conditional color
- [x] Condition 1: if average increase above budget => icon: unsmile & red;
- [x] Condition 2: if average increase under budget => icon: smile & yellow;
- [x] Optimize styling - category-fields - category-pages
- [x] Create input-page for change the personal-budget of each category
