### ISSUE TITLE
2. Header with smile-icon and speech-bubble

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#2]
## Value proposition

**As a** user,
**I want to** to get direct visual and friendly feedback befor and after the data submit
**so that** I know that an input is desired and if my entry was submitted successfully

## Description

<img width="544" alt="img2" src="https://user-images.githubusercontent.com/104724279/175507977-04076997-aa16-43e2-a355-68504ae822b3.png">

## Acceptance criteria

- [x] Header stay on top and smile-icon is placed correctly
- [x] Speech-bubble display call-to-action text befor sending data
- [x] Speech-bubble show confirm-message after data-input

## Complexity

Small to medium

## Tasks

- [x] Setup: branch, component, storybook, specs
- [x] Create a header on top with a centered smile icon
- [x] Create a Speech-bubble with integrated textfield
- [x] Add base styles
- [x] Implement an system which handles the messages

**Comment by JessicaLoers** [comment]
**Hi Kim**
It' me again  👋

I have a bunch of very, very mean questions. 🫣
Please take some time to think about my questions and revise your User Story.  
I am curious what your smiley looks like later on. 

- What does the smiley or the speech bubble refer to? 
- What information is displayed in the speech bubble? 
- Is this one of your core feature of your app? 

**Acceptance criteria**
-  Header stay on top and smile-icon is placed correctly_ **_what means correctly?  Centered? _**  
-  Speech-bubble show correct massage / information: **_which message is correct? Which should be displayed?_**
-  Header is fixed on the top of the screen: **_This criteria is redundant (see first criteria: header stays/remains on top)_**
-  Speech-bubble / Textbox is placed in correct position and visible:  **_what means correct position?  Is the speech bubble always visible?_**

**Tasks**
-  Show a smile-icon on the top with hint-text to common-state: **_what means common-state?_**  
-  Implement an system which handles the messages: **_just a typo "Implement a system.."_**

**Comment by smilenow24** [comment]
@JessicaLoers - Thank you very much for your good review,
the smile icon is part of a core feature of my app - a reward system.
The icon will be continuously visible and will be further developed later.
Later (in the speech-bubble) can then be hints about the respective context or other status messages. 
In addition, the icon can then also change its facial expressions and color.

I have taken your hints into account and updated the user story accordingly.

Thanks and greetings Kim

**Comment by JessicaLoers** [comment]
Well done, @smilenow24 ✌️

I would recommend that you revise the value proposition, because as you described it will be a reward system.  _Here is an idea you could think about:_

**As a** user
**I want a** direct visual and friendly feedback of my interactions/data submit
**So that I** know if my interaction/entry was submitted successfully

I would elaborate on the **acceptance criteria** for this User Story.  
If I understand it correctly, the smiley feature is to be extended in subsequent user stories. But what are the criteria in the **current version of your app**? 
As a developer, I wouldn't know how to implement  the speech message 

**Acceptance criteria**
- What text is displayed in the different speech bubbles? Regarding the entry of electricity consumption, because that is the only feature so far. (e.g. "Your data is added", "Please add your data", ... )
- When will the speech bubble disappear ? Or does it remain visible until the next interaction?
- What happens if the submit doesn't work? 
- ... _overall be more specific_ 😉

If you want to extend the functionality of the smiley, you can write more user stories later. Therefore, I would recommend that you also name the title of the user story more specifically.

**If you have any questions, feel free to ask.**

**Comment by smilenow24** [comment]
Thank you ✌️,
currently I want to keep this feature as small as possible; 
therefore actual only call-to-action and confirm-message; 
whenever the app grows, this feature should then grow accordingly;
I have updated the issue, but some hints i will use later; 
greetings
