### ISSUE TITLE
3. Display first category for input data

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#3]
## Value proposition

**As a** user,
**I want to** get displayed the first category for input
**so that** I can click on them to switch to the input dialog.

## Description

<img width="500" alt="img3" src="https://user-images.githubusercontent.com/104724279/176449469-bd9ed46a-e9a2-4d21-8b6b-02379c2afb4a.png">

## Acceptance criteria

- [x] Category-menu is showed with icon
- [x] Category-menu is centered and flex
- [x] "Category-site" is not scrollable
- [x] Back-button is only visible on "input-dialog-site"

## Complexity

Small to medium

## Tasks

- [x] Setup: branch, component, storybook, specs
- [x] Touch on Button at first category to jump to "input-dialog-site"
- [x] Create "category-site" with the first category
- [x] Category gets an unique icon and button-symbol
- [x] Place a back-button in the header to jump back to "category-site"
