### ISSUE TITLE
4. Basic calculations based on consumption input data

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#4]
## Value proposition

**As a** user,
**I want to** to get displayed some calculations based on consumption data inputs
**so that** I can see the actual increase, the total consumption, sum of entries and the daily average

## Description

<img width="410" alt="img-calc2" src="https://user-images.githubusercontent.com/104724279/177006386-4ef0a262-a5f5-4a52-bb2a-9812ff1a30ca.png">

## Acceptance criteria

- [x] Display increase 
- [x] Display total consumption
- [x] Display daily average (rounded)
- [x] Display total entries
- [x] Check storybook
- [x] Spec is OK

## Complexity

small to medium

## Tasks

- [x] Create branch
- [x] Calculation increase 
- [x] Calculation total consumption
- [x] Calculation daily average
- [x] Show sum of entries
- [x] Create a spec
