### ISSUE TITLE
6. Implement Categories - heating & mobility - with category field and navigation

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#6]
## Value proposition

**As a** user,
**I want to** get displayed the categories heating and mobility
**so that** so that I can also track and evaluate my energy consumption for heating and mobility

## Description

<img width="594" alt="img-cat-heating" src="https://user-images.githubusercontent.com/104724279/178148720-72486669-506f-4fe1-9b98-663d13535d02.png">
<img width="591" alt="img-cat-car" src="https://user-images.githubusercontent.com/104724279/179466818-5cd3350f-e49c-4c8f-a4ad-a1dbaf4ab609.png">

## Acceptance criteria

- [x] Category-fields is visible and shows calculation
- [x] Category-fields-button links to input-dialog for heating consumption
- [x] Category input-dialogs works fine
- [x] Toggle-buttons is visible and switching between charts works fine

## Complexity

large

## Tasks

- [x] Create branch
- [x] Create new button-fields on dashboard
- [x] Adapt button-fields with according variables / icon / button-link
- [x] Implement navigation with npm router - install and code reconstruction
- [x] Use useNavigate for return-button
- [x] Reconstruction of input-object for implementation of further categories
- [x] Adapt call of input data according to the new object structur (for both categories)
- [x] Implement a toggle-button for switching between line- and barchart
- [x] Implement start-site with loading-animation
- [x] Adjust the styles
- [x] Refactoring App.js

**Comment by smilenow24** [comment]
Hallo

**Comment by smilenow24** [comment]
Hello World!
