### ISSUE TITLE
9. Implement local-storage

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#7]
## Value proposition

As a user,
I want to have my data inputs saved in the browser
so that I don't loose my progress in between reloads

## Description

-/-

## Acceptance criteria

- [ ] Data inputs will be saved with localStorage
- [ ] Saving takes place immediately for each change

## Complexity

small to medium

## Tasks

- [ ] Create branch
- [ ] Add hook for localStorage
