### ISSUE TITLE
5. Display analytical data - by calculation results and charts

### ISSUE THREAD

**Issue by smilenow24** [smilenow24/capstone-project#9]
## Value proposition

**As a** user,
**I want to** to get displayed calculation results and charts based on the consumption data inputs
**so that** so that I get a numeric and graphical overview for an evaluation of the input data;

## Description

<img width="360" alt="img-chart1" src="https://user-images.githubusercontent.com/104724279/177165305-487df97e-6402-4f54-8017-f012a4e8ada0.png">
<img width="449" alt="img-calc-analytic values" src="https://user-images.githubusercontent.com/104724279/178249920-489400ae-b9c6-41c6-bde9-3f0a32909a35.png">

## Acceptance criteria

- [x] Display calculation result: daily average increase, rest budget
- [x] Display line-chart with x-axis(time) and y-axis(value)
- [x] Display bar-chart with x-axis(time) and y-axis(value)
- [x] Show total budget and rest budget
- [x] Show daily average increase
- [x] Show saldo increase value  
- [x] Values: absolute and average daily consumption
- [x] Time: per day

## Complexity

medium to large

## Tasks

- [x] Create branch
- [x] Write date or time calculation as a basis for calculations
- [x] Calculation: daily average increase, total- & rest-budget
- [x] Calculation of saldo increase value 
- [x] Conditional styling 1: if daily average increase > daily-budget ? red : green
- [x] Conditional styling 2: if saldo increase value  > daily-budget ? red : green 
- [x] Install and implement "chartjs"
- [x] Connect data with "chartjs-hook"
- [x] Add options for the Chart
- [x] Implement a line-chart which works with the current data
- [x] Implement calculation of chart-data 
- [x] Add chart within the input-dialog
